<?php
/**
 * @category Mageants ExtraFee
 * @package Mageants_ExtraFee
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Tab\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div id="order-messages">
    <?= /* @noEscape */ $block->getChildHtml('order_messages') ?>
</div>
<?= /* @noEscape */ $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= /* @noEscape */ $_order->getId() ?>"/>

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method
            <?php if ($_order->getIsVirtual()): ?>
                order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */ __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= /* @noEscape */ $block->getPaymentHtml() ?>
                </div>
                <div class="order-payment-currency">
                     <?= /* @noEscape */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional">
                    <?= /* @noEscape */ $block->getChildHtml('order_payment_additional'); ?>
                    <?= /* @noEscape */ $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?= /* @noEscape */ $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>
<?= $block->getChildHtml('order_additional_info') ?>

<?= /* @noEscape */ $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Items Ordered') ?></span>
    </div>
    <?= /* @noEscape */ $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */ __('Notes for this Order') ?></span>
            </div>
            <?= /* @noEscape */ $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */ __('Order Totals') ?></span>
            </div>
            <?= /* @noEscape */ $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= /* @noEscape */ $block->getChildHtml('popup_window');?>

<script>
require([
    "prototype",
    "Magento_Sales/order/giftoptions_tooltip"
], function(){

//<![CDATA[
    /**
     * Retrieve gift options tooltip content
     */
    function getGiftOptionsTooltipContent(itemId) {
        var contentLines = [];
        var headerLine = null;
        var contentLine = null;

        $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function (element) {
            if (element.down(0)) {
                headerLine = element.down(0).innerHTML;
                contentLine = element.down(0).next().innerHTML;
                if (contentLine.length > 30) {
                    contentLine = contentLine.slice(0,30) + '...';
                }
                contentLines.push(headerLine + ' ' + contentLine);
            }
        });
        return contentLines.join('<br/>');
    }
    giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
    window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
//]]>

});
</script>
