<?php
/**
 * @category Mageants ImageGallery
 * @package Mageants_ImageGallery
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@mageants.com>
 */

$viewModel = $block->getData('view_model');
$helper = $viewModel->getHelper();
if ($helper->isEnabled()) {
    ?>
<div class="page-title"><span>
    <h3 style="background-color: <?= /* @noEscape */ $helper->getHeaderBgColor();?>; 
    color:<?= /* @noEscape */ $helper->getHeaderForeColor();?>;">
        <?= /* @noEscape */ __($helper->getHeaderTitle()); ?></h3></span></div>
<div class="gallery-action">
<a id="back" style="display:none"><?= /* @noEscape */ __("Back")?></a>
<a class="images_gallery_button" style="display:none"><?= /* @noEscape */ __("Images")?></a>
<a class="videos_gallery_button" style="display:none;"><?= /* @noEscape */ __("Videos")?></a>
</div>
<div id="images_gallery"></div>
<div id="gallery_image">
    <?php $url = '' ?>
    <?php $collection=$helper->getCategories();
    
    if (count($collection) > 0) {
        foreach ($collection as $category) {
            $categoryid=$category['category_id'];
            $url = preg_replace('#[^0-9a-z]+#i', '-', $category['url_key']);
            $url = $block->getBaseUrl()."imagegallery/".$url.".html";

            ?>
            <div class="uniq">
                <a id="<?= /* @noEscape */ $category['category_id']; ?>" href="<?= /* @noEscape */ $url?>">    
                    <img id="image_id" src='<?= /* @noEscape */ $helper->getCategoryImageUrl($categoryid); ?>' 
                    title="<?= /* @noEscape */ $category['category_name']; ?>" alt='' width="300" />
                </a>
                <input type="hidden" class="category_url" value="<?= /* @noEscape */ $url?>" />
                <h2 style="background:<?= /* @noEscape */ $helper->getImageTitleBgColor();?>;">
                    <a style="color:<?= /* @noEscape */ $helper->getImageTitleForeColor();?>;" 
                    id="<?= /* @noEscape */ $category['category_id']; ?>" 
                    href="<?= /* @noEscape */ $url?>"> <?= /* @noEscape */ $category['category_name']; ?></a>
                    <input type="hidden" class="category_url" value="<?= /* @noEscape */ $url?>" />
                </h2>
            </div>
            <?php
        }
    } else {?>
        <?= /* @noEscape */ __('No Image Category Found');
    }?>
</div>
<div class="loader"></div>
<div id="myModal" class="modal" style="display:none">
    <img class="modal-content zoomIn animated" id="imagegallery">    
</div>    
<?php } else {?>
    <?= /* @noEscape */ '<h2>'.__('Please Enabled ImageGallery Module First....... :-)').'</h2>';
}
?>
<script>
    require(['jquery'],function($){
        $(document).ready(function(){
            var imageUrl="<?= /* @noEscape */ $block->getViewFileUrl('Mageants_ImageGallery::images/hour.gif'); ?>";
            $('.loader').css({'background':'url(' + imageUrl +') 50% 50% no-repeat rgb(249,249,249)','display':'none'});
            $('#back').click(function() {
                $('.page-title span h3').text("<?= /* @noEscape */ __("Image Gallery"); ?>");
                $('#images_gallery').html('');
                $('#gallery_image').removeClass('displayval');
                $(this).css("display","none");
                $('.images_gallery_button').css("display","none");
                $('.videos_gallery_button').css("display","none");
                $url = '<?= /* @noEscape */ $block->getBaseUrl()."imagegallery/"; ?>';
                window.location.href = $url;
            });

            $('.images_gallery_button').click(function() {
                var id = $(this).attr('id');
                $('.loader').css("display","block");
                $.ajax({
                    type: 'POST',
                    url: '<?= /* @noEscape */ $block->getUrl('imagegallery/index/index'); ?>',
                    data: { categoryid: id},
                    success: function(response) {
                        $('#images_gallery').html(response);
                    },
                    complete: function(){
                        $('.loader').css("display","none");
                    }
                });
            });

            $('.videos_gallery_button').click(function() {
                var id = $(this).attr('id');
                $('.loader').css("display","block");
                $.ajax({
                    type: 'POST',
                    url: '<?= /* @noEscape */ $block->getUrl('imagegallery/index/videos'); ?>',
                    data: { categoryid: id},
                    success: function(response) {
                        $('#images_gallery').html(response);
                    },
                    complete: function(){
                        $('.loader').css("display","none");
                    }
                });
            });        
        });
        
        
    });
</script>
