<?php
/**
 * @category  Mageants Orderattribute
 * @package   Mageants_Orderattribute
 * @copyright Copyright (c) 2020 Mageants
 * @author    Mageants Team <support@Mageants.com>
 */
?>

<div class="admin__page-section-title">
    <span class="title"><?= $block->escapeHtml(__('Order Attributes')) ?></span>
    <div class="actions"></div>
</div>
<div id="order-attributes-fields"
     class="admin__page-section-content admin__scope-old">
     <?= /* @noEscape */ $block->getFormHtml() ?>
</div>

<script>
    require([
        "jquery",
        "mage/calendar"
    ], function($){
        $('.date-calendar').each(function(key, item) {
            var calendar = $(item).data('mage-init');
            if(calendar) {
                $(item).calendar(calendar.calendar);
            }
        });
    });
</script>
