<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Shipping\Block\Adminhtml\View\Form $block
 */
$order = $block->getShipment()->getOrder();
$viewModel = $block->getData('view_model');
$orderId = $order->getId();
$displayAt = $viewModel->getDisplayPosition($orderId);
$isEnable = $viewModel->getPluginEnable();
$productData = $viewModel->productData();
$taxValues = $viewModel->getTaxModel();
$shippingValue = $viewModel->getShippingModel();
$popupValue = $block->escapeUrl($shippingValue->getTrackingPopupUrlBySalesModel($block->getShipment()));
?>
<?= $block->getChildHtml('order_info'); ?>
<section class="admin__page-section order-shipment-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Payment &amp; Shipping Method')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Payment Information')); ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div><?= $block->getChildHtml('order_payment') ?></div>
                <div class="order-payment-currency">
                    <?= $block->escapeHtml(__('The order was placed using %1.', $order->getOrderCurrencyCode())); ?>
                </div>
            </div>
        </div>

        <div class="admin__page-section-item order-shipping-address">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Shipping and Tracking Information')); ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="shipping-description-wrapper">
                    <?php if ($block->getShipment()->getTracksCollection()->count()): ?>
                        <p>
                            <a href="#" id="linkId"
                             onclick="popWin('<?= /* @noEscape */  $popupValue; ?>'
                             ,'trackshipment','width=800,height=600,resizable=yes,scrollbars=yes')"
                              title="<?= $block->escapeHtml(__('Track this shipment')); ?>">
                                <?= $block->escapeHtml(__('Track this shipment')); ?>
                            </a>
                        </p>
                    <?php endif; ?>
                    <div class="shipping-description-title">
                        <?= $block->escapeHtml($order->getShippingDescription()); ?>
                    </div>

                    <?= $block->escapeHtml(__('Total Shipping Charges')); ?>:

                    <?php if ($taxValues->displayShippingPriceIncludingTax()): ?>
                        <?php $excl = $block->displayShippingPriceInclTax($order); ?>
                    <?php else: ?>
                        <?php $excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $incl = $block->displayShippingPriceInclTax($order); ?>

                    <?= /* @noEscape */ $excl; ?>
                    <?php if ($taxValues->displayShippingBothPrices() && $incl != $excl): ?>
                        (<?= $block->escapeHtml(__('Incl. Tax')); ?> <?= /* @noEscape */ $incl; ?>)
                    <?php endif; ?>
                </div>

                <p>
                    <?php if ($block->canCreateShippingLabel()): ?>
                        <?= /* @noEscape */ $block->getCreateLabelButton(); ?>
                    <?php endif ?>
                    <?php if ($block->getShipment()->getShippingLabel()): ?>
                        <?= /* @noEscape */ $block->getPrintLabelButton(); ?>
                    <?php endif ?>
                    <?php if ($block->getShipment()->getPackages()): ?>
                        <?= /* @noEscape */ $block->getShowPackagesButton(); ?>
                    <?php endif ?>
                </p>
                <?= $block->getChildHtml('shipment_tracking'); ?>

                <?= $block->getChildHtml('shipment_packaging'); ?>
                <script>
                    require([
                        'jquery',
                        'prototype'
                    ], function(jQuery) {
                        var setCallbacks = function() {
                            window.packaging.setConfirmPackagingCallback(function() {
                                window.packaging.sendCreateLabelRequest();
                            });
                            window.packaging.setLabelCreatedCallback(function() {
                                setLocation("<?= /* @noEscape */  $block->escapeUrl(
                                    $block->getUrl(
                                        'adminhtml/order_shipment/view',
                                        ['shipment_id' => $block->getShipment()->getId()]
                                    )
                                ); ?>");
                            });
                        };

                        if (jQuery(document).data('packagingInited')) {
                            setCallbacks();
                        } else {
                            jQuery(document).on('packaging:inited', setCallbacks);
                        }
                    });
                </script>
            </div>
        </div>
    </div>
</section>
<?php
if ($isEnable) {
    ?>
    <section class="admin__page-section order-view-billing-shipping">
        <div class="admin__page-section-title">
            <span class="title"><?=  /* @noEscape */ __('Delivery Date Information') ?></span>
        </div>
        <?php if ($displayAt == 3) {
            $dateDeliveryData = [];
            $deliverydate = json_decode($order->getDeliveryDate());
            $deliverytime = json_decode($order->getDeliveryTimeslot());
            $deliverycomment = json_decode($order->getDeliveryComment());
            foreach ($deliverydate as $key => $productId) {
                $product = $productData->getById($deliverydate[$key]->item_id);
                $dateDeliveryData[$key]['productId'] =  $product->getId();
                $dateDeliveryData[$key]['productName'] =  $product->getName();
                $dateDeliveryData[$key]['deliverydate'] = $deliverydate[$key]->delivery_date;
                $dateDeliveryData[$key]['deliverytime'] = $deliverytime[$key]->delivery_timeslot;
                $dateDeliveryData[$key]['deliverycomment'] = $deliverycomment[$key]->delivery_comment;
            }
            foreach ($dateDeliveryData as $key => $value) {

                ?>
                <div class="admin__page-section-item-title">
                    <span class="title">Delivery Date</span>
                </div>
                <div id="product-name123">
                    <strong><?=  /* @noEscape */  __('Product Name') ?> : </strong>
                    <span class="price"><?=  /* @noEscape */ __($dateDeliveryData[$key]['productName']) ?></span>
                </div>
                <div id="delivery-date">
                    <strong><?=  /* @noEscape */  __('Shipping Arrival Date') ?> : </strong>
                    <span class="price"><?=  /* @noEscape */ __($dateDeliveryData[$key]['deliverydate']) ?></span>
                </div>
                <?php if ($dateDeliveryData[$key]['deliverytime'] != null
                || $dateDeliveryData[$key]['deliverytime'] != '') { ?>
                    <div id="delivery-timeslot">
                        <strong><?= /* @noEscape */  __('Shipping Arrival Timeslot') ?> : </strong>
                        <span class="price"><?=/* @noEscape */ $dateDeliveryData[$key]['deliverytime'] ?></span>
                    </div>
                <?php }
                if ($dateDeliveryData[$key]['deliverycomment'] != null) { ?>
                    <div id="delivery-comment">
                        <strong><?=  /* @noEscape */  __('Shipping Arrival Comment') ?> : </strong>
                        <span class="price"><?= /* @noEscape */ $dateDeliveryData[$key]['deliverycomment'] ?></span>
                    </div>
                <?php } ?>
                <br>
            <?php }
        } else {
            ?>
            <div class="admin__page-section-item-title">
                <span class="title">Delivery Date</span>
            </div>

            <div id="delivery-date">
                <strong><?=  /* @noEscape */  __('Shipping Arrival Date') ?> : </strong>
                <span class="price"><?=  /* @noEscape */ __($order->getDeliveryDate()) ?></span>
            </div>
            <?php if ($order->getDeliveryTimeslot() != null || $order->getDeliveryTimeslot() != '') { ?>
                <div id="delivery-timeslot">
                    <strong><?=  /* @noEscape */  __('Shipping Arrival Timeslot') ?> : </strong>
                    <span class="price"><?=/* @noEscape */ $order->getDeliveryTimeslot() ?></span>
                </div>
            <?php } ?>
            <?php if ($order->getDeliveryComment() != null) { ?>
                <div id="delivery-comment">
                    <strong><?=  /* @noEscape */  __('Shipping Arrival Comment') ?> : </strong>
                    <span class="price"><?=/* @noEscape */ $order->getDeliveryComment() ?></span>
                </div>
            <?php } ?>
        <?php } ?>
    </section>
<?php } ?>
<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Items Shipped')); ?></span>
    </div>
    <?= $block->getChildHtml('shipment_items'); ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('Order Total')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <?= $block->getChildHtml('shipment_packed'); ?>

        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= $block->escapeHtml(__('Shipment History')); ?></span>
            </div>
            <div class="admin__page-section-item-content"><?= $block->getChildHtml('order_comments'); ?></div>
        </div>
    </div>
</section>