<?php

/** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Info */ ?>
<?php $_order = $block->getOrder();

$viewModel = $block->getData('view_model');
$orderId = $_order->getId();
$displatAt = $viewModel->getDisplayPosition($orderId);
$isEnable = $viewModel->getPluginEnable();
$productData = $viewModel->productData();
$urlBuilder = $viewModel->getUrl();
?>

<div id="order-messages">
    <?= /* @noEscape */ $block->getChildHtml('order_messages') ?>
</div>

<?= /* @noEscape */ $block->getChildHtml('order_info') ?>
<input type="hidden" name="order_id" value="<?= /* @noEscape */ $_order->getId() ?>" />

<section class="admin__page-section order-view-billing-shipping">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item
        order-payment-method<?php if ($_order->getIsVirtual()): ?>
             order-payment-method-virtual<?php endif; ?>">
            <?php /* Payment Method */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */ __('Payment Information') ?></span>
            </div>
            <div class="admin__page-section-item-content">
                <div class="order-payment-method-title"><?= /* @noEscape */ $block->getPaymentHtml() ?></div>
                <div class="order-payment-currency">
                    <?= /* @noEscape */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?>
                </div>
                <div class="order-payment-additional">
                    <?= /* @noEscape */ $block->getChildHtml('order_payment_additional'); ?>
                    <?= /* @noEscape */ $block->getChildHtml('payment_additional_info'); ?>
                </div>
            </div>
        </div>
        <?= /* @noEscape */ $block->getChildHtml('order_shipping_view') ?>
    </div>
</section>
<?php if ($isEnable) { ?>
    <!-- add by me -->
    <section class="admin__page-section order-view-billing-shipping">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @noEscape */ __('Delivery Date Information') ?></span>
        </div>
        <?php if ($displatAt == 3) {
            $dateDeliveryData = [];
            $deliverydate = json_decode($_order->getDeliveryDate());
            $deliverytime = json_decode($_order->getDeliveryTimeslot());
            $deliverycomment = json_decode($_order->getDeliveryComment());
            if ($_order->getDeliveryStatus() != null) {
                $deliverystatus = json_decode($_order->getDeliveryStatus());
            }
            foreach ($deliverydate as $key => $productId) {
                $product = $productData->getById($deliverydate[$key]->item_id);
                $dateDeliveryData[$key]['productId'] =  $product->getId();
                $dateDeliveryData[$key]['productName'] =  $product->getName();
                $dateDeliveryData[$key]['deliverydate'] = $deliverydate[$key]->delivery_date;
                $dateDeliveryData[$key]['deliverytime'] = $deliverytime[$key]->delivery_timeslot;
                $dateDeliveryData[$key]['deliverycomment'] = $deliverycomment[$key]->delivery_comment;
                if (isset($deliverystatus)) {
                    $dateDeliveryData[$key]['deliverystatus'] = $deliverystatus[$key]->delivery_status;
                }
            }
            foreach ($dateDeliveryData as $key => $value) {

                ?>

                <div class="admin__page-section-item-title">
                    <span class="title">Delivery Date</span>
                    <div class="actions">
                        <a href="<?= /* @noEscape */ $urlBuilder
                                        ->getUrl(
                                            'delivery/information/edit',
                                            $paramsHere =
                                                [
                                                    'id' => $_order->getId(),
                                                    'productid' => $dateDeliveryData[$key]['productId']
                                                ]
                                        ); ?>">Edit</a>
                    </div>
                </div>
                <div id="product-name">
                    <strong><?= /* @noEscape */ __('Product Name') ?> : </strong>
                    <span class="price"><?= /* @noEscape */ __($dateDeliveryData[$key]['productName']) ?></span>
                </div>
                <div id="delivery-date">
                    <strong><?= /* @noEscape */ __('Shipping Arrival Date') ?> : </strong>
                    <span class="price"><?= /* @noEscape */ __($dateDeliveryData[$key]['deliverydate']) ?></span>
                </div>
                <?php if ($dateDeliveryData[$key]['deliverytime'] != null
                    || $dateDeliveryData[$key]['deliverytime'] != ''
                ) { ?>
                    <div id="delivery-timeslot">
                        <strong><?= /* @noEscape */ __('Shipping Arrival Timeslot') ?> : </strong>
                        <span class="price"><?=/* @noEscape */ $dateDeliveryData[$key]['deliverytime'] ?></span>
                    </div>
                <?php } ?>
                <?php if ($dateDeliveryData[$key]['deliverycomment'] != null) { ?>
                    <div id="delivery-comment">
                        <strong><?= /* @noEscape */ __('Shipping Arrival Comment') ?> : </strong>
                        <span class="price"><?=/* @noEscape */ $dateDeliveryData[$key]['deliverycomment'] ?></span>
                    </div>
                <?php } ?>

            <?php }
        } else {
            ?>
            <div class="admin__page-section-item-title">
                <span class="title">Delivery Date</span>
                <div class="actions">
                    <a href="<?= /* @noEscape */ $urlBuilder
                                    ->getUrl(
                                        'delivery/information/edit',
                                        $paramsHere = ['id' => $_order->getId()]
                                    ); ?>">Edit</a>
                </div>
            </div>
            <div id="delivery-date">
                <strong><?= /* @noEscape */ __('Shipping Arrival Date') ?> : </strong>
                <span class="price"><?= /* @noEscape */ __($_order->getDeliveryDate()) ?></span>
            </div>
            <?php if ($_order->getDeliveryTimeslot() != null) { ?>
                <div id="delivery-timeslot">
                    <strong><?= /* @noEscape */ __('Shipping Arrival Timeslot') ?> : </strong>
                    <span class="price"><?= /* @noEscape */$_order->getDeliveryTimeslot() ?></span>
                </div>
            <?php } ?>
            <?php if ($_order->getDeliveryComment() != null) { ?>
                <div id="delivery-comment">
                    <strong><?= /* @noEscape */ __('Shipping Arrival Comment') ?> : </strong>
                    <span class="price"><?=/* @noEscape */ $_order->getDeliveryComment() ?></span>
                </div>
            <?php } ?>
        <?php } ?>
    </section>
<?php } ?>
<!-- add by me end -->

<?= /* @noEscape */ $block->getGiftOptionsHtml() ?>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Items Ordered') ?></span>
    </div>
    <?= /* @noEscape */ $block->getItemsHtml() ?>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?= /* @noEscape */ __('Order Total') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-comments-history">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */ __('Notes for this Order') ?></span>
            </div>
            <?= /* @noEscape */ $block->getChildHtml('order_history') ?>
        </div>

        <div class="admin__page-section-item order-totals">
            <div class="admin__page-section-item-title">
                <span class="title"><?= /* @noEscape */ __('Order Totals') ?></span>
            </div>
            <?= /* @noEscape */ $block->getChildHtml('order_totals') ?>
        </div>
    </div>
</section>

<?= /* @noEscape */ $block->getChildHtml('popup_window'); ?>

<script>
    require([
        "prototype",
        "Magento_Sales/order/giftoptions_tooltip"
    ], function() {

        //<![CDATA[
        /**
         * Retrieve gift options tooltip content
         */
        function getGiftOptionsTooltipContent(itemId) {
            var contentLines = [];
            var headerLine = null;
            var contentLine = null;

            $$('#gift_options_data_' + itemId + ' .gift-options-tooltip-content').each(function(element) {
                if (element.down(0)) {
                    headerLine = element.down(0).innerHTML;
                    contentLine = element.down(0).next().innerHTML;
                    if (contentLine.length > 30) {
                        contentLine = contentLine.slice(0, 30) + '...';
                    }
                    contentLines.push(headerLine + ' ' + contentLine);
                }
            });
            return contentLines.join('<br/>');
        }
        giftOptionsTooltip.setTooltipContentLoaderFunction(getGiftOptionsTooltipContent);
        window.getGiftOptionsTooltipContent = getGiftOptionsTooltipContent;
        //]]>

    });
</script>