<?php
/**
 * @category  Mageants Orderattribute
 * @package   Mageants_Orderattribute
 * @copyright Copyright (c) 2020 Mageants
 * @author    Mageants Team <support@Mageants.com>
 */
?>
<?php
/** @var $block \Mageants\Orderattribute\Block\Adminhtml\Order\Attribute\Edit\Tab\Options\Options */
?>
<fieldset class="fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Options (values of your attribute)')) ?></span>
    </legend>
    <div id="manage-options-panel">
        <table class="admin__control-table">
            <thead>
                <tr id="attribute-options-table">
                    <th class="col-draggable"></th>
                    <th class="col-default control-table-actions-th">
                        <?= $block->escapeHtml(__('Is Default')) ?>
                        <div>(
                            <a class="mg-unselect-default"><?= $block->escapeHtml(__('Unselect All')) ?></a>
                            )
                        </div>
                    </th>
                    <?php
                    $storeList = $block->getStores();
                    foreach ($storeList as $_store):
                        ?>
                        <th><?= $block->escapeHtml(__($_store->getName())) ?></th>
                    <?php endforeach;
                    $storetotal = count($storeList) + 3;
                    ?>
                    <th class="col-delete">&nbsp;</th>
                </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= /* @noEscape */ $storetotal ?>" class="validation">
                   <input type="hidden" class="required-dropdown-attribute-entry" name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= /* @noEscape */ $storetotal ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                        <button id="add_new_option_button"
                                title="<?= $block->escapeHtmlAttr('Add Option') ?>"
                                type="button" class="action- scalable add">
                             <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
         <tr>
            <td class="col-draggable">
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()): ?>
                    <div data-role="draggable-handle" class="draggable-handle"
                         title="<?= $block->escapeHtml(__('Sort Option')) ?>"></div>
                <?php endif; ?>
                <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"
                       value="<%- data.sort_order %>"
                        <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?>
                            disabled="disabled"
                        <?php endif; ?>
                />
            </td>
            <td class="col-default control-table-actions-cell">
                <input class="input-radio" type="<%- data.intype %>" name="default[]"
                       value="<%- data.id %>" <%- data.checked %>
                <?php if ($block->getReadOnly()):?>
                    disabled="disabled"
                <?php endif;?>
                />
            </td>
            <?php foreach ($block->getStores() as $_store): ?>
            <td class="col-<%- data.id %>">
                <input  name="option[value][<%- data.id %>][<?= /* @noEscape */ $_store->getId() ?>]"
                        value="<%- data.store<?= /* @noEscape */ $_store->getId() ?> %>"
                        class="input-text
                        <?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID):?>
                          required-option
                        <?php endif; ?>"
                        type="text"
                        <?php if ($block->getReadOnly() || $block->canManageOptionDefaultOnly()): ?>
                           disabled="disabled"
                        <?php endif;?>
                />
            </td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                    <button id="delete_button_<%- data.id %>"
                            title="<?= $block->escapeHtml(__('Delete')) ?>" type="button"
                            class="action- scalable delete delete-option"
                        >
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
    <?php
    $values = [];
    foreach ($block->getOptionValues() as $value) {
        array_push($values, $value->getData());
    }
    ?>
   
    <script>
        require([
            "jquery"
        ], function (jQuery) {
            jQuery('body').on(
                {'click': function(){
                    jQuery('input[name="default[]"]').removeAttr('checked');
                }},
                ".mg-unselect-default"
            );
        });
    </script>
    <?php
        $attributesData = json_encode($values);
        $isSortable = (int)(!$block->getReadOnly() && !$block->canManageOptionDefaultOnly());
        $isReadOnly = (int)$block->getReadOnly();
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Mageants_Orderattribute/js/attribute/options": {
                    "attributesData": <?= /* @noEscape */ $attributesData ?>,
                    "isSortable":  <?= /* @noEscape */ $isSortable ?>,
                    "isReadOnly": <?= /* @noEscape */ $isReadOnly ?>
                }
            }
        }
    </script>
</fieldset>
