<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$blockObj= $block->getLayout()->createBlock(\Mageants\OrderApprovalRules\Block\Frontend\OrderApprovalRules::class);
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($blockObj->checkVersion() == "2.3.0") { ?>
        <?php if ($block->getOrderId()):?>
            <?php if ($block->getCanViewOrder()):?>
                <p>
                    <?= /* @noEscape */ __(
                        'Your order number is: %1.',
                        sprintf(
                            '<a href="%s" class="order-number"><strong>%s</strong></a>',
                            $block->escapeHtml($block->getViewOrderUrl()),
                            $block->escapeHtml($block->getOrderId())
                        )
                    ) ?>
                </p>
            <?php  else: ?>
                <p>
                    <?= /* @noEscape */ __(
                        'Your order # is: <span>%1</span>.',
                        $block->escapeHtml($block->getOrderId())
                    ) ?>
                </p>
            <?php endif;?>
                <p>
                    <?= /* @noEscape */ __('We\'ll email you an order confirmation with details and tracking info.') ?>
                </p>
            <?php else:?>
                <?php if ($blockObj->getOrderIncrementId()):?>
                    <p>
                        <?= /* @noEscape */ __(
                            'Your order number is: %1.',
                            sprintf(
                                '<a href="%s" class="order-number"><strong>%s</strong></a>',
                                $blockObj->getViewOrderUrl(),
                                $blockObj->getOrderIncrementId()
                            )
                        ) ?>
                    </p>
                    <p>
                        <?= /* @noEscape */
                        __('We\'ll email you an order confirmation with details and tracking info.') ?>
                    </p>
                <?php endif;?>
        <?php endif;?>
    <?php } else { ?>
        <?php if ($block->getOrderId()):?>
            <?php if ($blockObj->getOrderIncrementId()):?>
                <p>
                    <?= /* @noEscape */ __(
                        'Your order number is: %1.',
                        sprintf(
                            '<a href="%s" class="order-number"><strong>%s</strong></a>',
                            $blockObj->getViewOrderUrl(),
                            $blockObj->getOrderIncrementId()
                        )
                    ) ?>
                </p>
                    <p>
                        <?= /* @noEscape */
                        __('We\'ll email you an order confirmation with details and tracking info.') ?>
                    </p>
            <?php else: ?>
                <?php if ($block->getCanViewOrder()):?>
                        <p>
                            <?= /* @noEscape */ __(
                                'Your order number is: %1.',
                                sprintf(
                                    '<a href="%s" class="order-number"><strong>%s</strong></a>',
                                    $block->escapeHtml($block->getViewOrderUrl()),
                                    $block->escapeHtml($block->getOrderId())
                                )
                            ) ?>
                        </p>
                <?php  else:?>
                        <p><?= /* @noEscape */
                        __('Your order # is: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?>
                        </p>
                <?php endif;?>
                        <p><?= /* @noEscape */
                        __('We\'ll email you an order confirmation with details and tracking info.') ?>
                        </p>
            <?php endif;?>
        <?php endif;?>
    <?php } ?>
    <?= $block->getAdditionalInfoHtml() ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= /* @noEscape */
                $block->getContinueUrl() ?>">
                <span>
                    <?= /* @noEscape */ __('Continue Shopping') ?>
                </span>
            </a>
        </div>
    </div>
</div>
<?php
    $blockObj->removeSession();
?>
