<?php
$helper = $this->helper('Mageants\FacebookChat\Helper\Data');
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$request = $objectManager->get('\Magento\Framework\App\Request\Http');

$isEnable = $helper->isEnable();
$loginMessage = $helper->getLoginMsg();
$logoutGreeting = $helper->getGuestMsg();
$facebookPageid = $helper->getFacebookPageId();
$themeColor = $helper->getThemeColor();
$displayAt = $helper->getDisplayAt();

?>

<?php if ($isEnable):
	if ($displayAt == "all_page" || $displayAt == $request->getFullActionName()):?>
			<div class="fb-customerchat"
			 attribution=setup_tool
			 theme_color="<?php echo $themeColor; ?>"
			 logged_in_greeting="<?php echo $loginMessage; ?>"
			 logged_out_greeting="<?php echo $logoutGreeting; ?>"
			 page_id="<?php echo $facebookPageid; ?>"></div>
		<?php
	endif;
endif; ?>

<!-- Load Facebook SDK for JavaScript -->
<script>
window.fbAsyncInit = function() {
	FB.init({
		xfbml            : true,
		version          : 'v15.0'
	});
};

(function(d, s, id) {
	var js, fjs = d.getElementsByTagName(s)[0];
	if (d.getElementById(id)) return;
	js = d.createElement(s); js.id = id;
	js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
	fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
</script>