<?php
/**
 * @category Mageants FastOrder
 * @package Mageants_FastOrder
 * @copyright Copyright (c) 2018 Mageants
 * @author Mageants Team <support@mageants.com>
 */
?>

<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $sortOrder = $block->getSortOrder(); ?>
<div class="table-wrapper grouped">
    <table class="table data grouped" id="mageants-fastorder-super-product-table">
        <caption class="table-caption"><?= /*@noEscape */ __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?= /*@noEscape */ __('Product Name') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?= /*@noEscape */__('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): ?>
            <?php foreach ($_associatedProducts as $_item): ?>
        <tbody>
            <tr>
                <td data-th="<?= /*@noEscape */$block->escapeHtml(__('Product Name')); ?>" class="col item">
                    <strong class="product-item-name">
                    <?= /*@noEscape */ $block->escapeHtml($_item->getName()) ?>
                    </strong>
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?= /*@noEscape */ $block->getProductPrice($_item) ?>
                        <?php endif; ?>
                        <?php endif; ?>
                </td>
                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?= /*@noEscape */$block->escapeHtml(__('Qty')); ?>" class="col qty">
                    <?php if ($_item->isSaleable()): ?>
                    <div class="control qty">
                        <?php $product_qty = $_item->getQty(); ?>
                        <?php
                            $this_product_id = $_product->getId();
                            $set_product_id = "";
                            $fast_group_option = "";
                        if (isset(${'_COOKIE'}['mgantsproduct_id'])) {
                            $set_product_id = ${'_COOKIE'}['mgantsproduct_id'];
                        }
                        if (isset(${'_COOKIE'}['fastorder_options_val'])) {
                            $fast_group_option = ${'_COOKIE'}['fastorder_options_val'];
                        }
                        if ($set_product_id == $this_product_id) {
                            $fast_group_option_array = explode(",", $fast_group_option);
                            foreach ($fast_group_option_array as $option_array) {
                                if ($option_array != "") {
                                    $options = explode('=>', $option_array);
                                    if (in_array($_item->getId(), $options)) {
                                        $product_qty = $options[1];
                                    }
                                }
                            }
                        }
                        ?>
                        <input type="number" 
                        name="mageants-fastorder-super_group[<?= /*@noEscape */
                        $sortOrder;?>][<?= /*@noEscape */ $_item->getId() ?>]"
                               data-selector="mageants-fastorder-super_group[<?= /*@noEscape */$_item->getId() ?>]"
                               data-selectore-id = "<?= /*@noEscape */ $_item->getId() ?>"
                               maxlength="12"
                               value="<?= /*@noEscape */ $product_qty * 1 ?>"
                               title="<?= /*@noEscape */ __('Qty') ?>"
                               class="input-text qty mageants-attribute-select"/>
                        <input type="hidden" class="mageants-child-price" data-excl-tax="" value="">
                    </div>
                <?php else: ?>
                    <div class="stock unavailable" title="<?= /*@noEscape */__('Availability') ?>">
                        <span><?= /*@noEscape */ __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <?php endif; ?>
            </tr>
                 <?php if ($block->getCanShowProductPrice($_product)
                    && $block->getCanShowProductPrice($_item)
                    && trim($block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                    ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?= /*@noEscape */ $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
        <?php endforeach; ?>
        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else: ?>3<?php endif; ?>">
                    <?= /*@noEscape */ __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="mageants-validation-message-box">
    <div class="mageants-mage-error"><?= /*@noEscape */ __('Please specify the quantity of product(s).') ?></div>
</div>
<script>
  require(["jquery", "jquery/ui", "mgants/fastorder_grouped"], function ($) {
    $(document).ready(function(){
        $('.mageants-product-info-price .price-box').remove();
    });
    $('#mageants-fastorder-super-product-table').fastorder_grouped({
        "mageantsqtyElement":"input.mageants-attribute-select",
        "sortOrder":'<?= /*@noEscape */ $sortOrder ?>',
    });
  });
</script>