<?php
/**
 * @category Mageants ExtraFee
 * @package Mageants_ExtraFee
 * @copyright Copyright (c) 2017 Mageants
 * @author Mageants Team <support@mageants.com>
 */

/**
 * @see \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer
 */

/** @var $block \Magento\Bundle\Block\Adminhtml\Sales\Order\View\Items\Renderer */
?>

<?php $_item = $block->getItem() ?>
<?php $items = array_merge([$_item], $_item->getChildrenItems()); ?>
<?php $_count = count($items) ?>
<?php $_index = 0 ?>

<?php $_prevOptionId = '' ?>

<?php if ($block->getOrderOptions() || $_item->getDescription() || $block->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $block->setPriceDataObject($_item) ?>
    <?php $attributes = $block->getSelectionAttributes($_item) ?>
    <?php if ($_item->getParentItem()): ?>
        <?php if ($_prevOptionId != $attributes['option_id']): ?>
        <tr>
            <td class="col-product"><div class="option-label">
                <?= /* @noEscape */ $attributes['option_label'] ?></div></td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last">&nbsp;</td>
        </tr>
            <?php $_prevOptionId = $attributes['option_id'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr<?= (++$_index==$_count && !$_showlastRow)?' class="border"':'' ?>>
        <?php if (!$_item->getParentItem()): ?>
        <td class="col-product">
            <div class="product-title" id="order_item_<?= /* @noEscape */ $_item->getId() ?>_title">
                <?= $block->escapeHtml($_item->getName()) ?>
            </div>
            <div class="product-sku-block">
                <span><?= /* @noEscape */ __('SKU') ?>:</span>
                <?= /* @noEscape */
                    $block->getCatalogdata($block->getSku());
                ?>
            </div>
            <!-- ExtraFee Block Start -->
            <?php $feesIds=$_item->getBuyRequest()->getFeesname();
                $price=$_item->getPrice();
            if (count($feesIds)>0) { ?>
                    <div class="extrafee-option">
                    <?php foreach ($feesIds as $fee) {
                        $feeData=$block->getFeeData($fee); ?>
                    <br/>
                    <span class="feesname"><?= /* @noEscape */ __($feeData['feesname']); ?></span>: <span>
                        <?php if ($feeData['type'] == 'Percentage') {
                            $amount=(($price*$feeData['amount'])/100); ?>
                            <?= /* @noEscape */ $block->getCurrency($amount); } else { ?>
                            <?= /* @noEscape */ $block->getCurrency($feeData['amount'], true, false);} ?> </span>    
                <?php } ?>
                    </div>
            <?php  } ?>
            <!-- ExtraFee Block End -->
        </td>
        <?php else: ?>
        <td class="col-product">
            <div class="option-value"><?= $block->getValueHtml($_item) ?></div>
        </td>
        <?php endif; ?>
        <td class="col-status">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $_item->getStatus() ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price-original">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('original_price') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-price">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'price') ?>
            <?php else: ?>
                    &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-ordered-qty">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= /* @noEscape */ __('Ordered') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyInvoiced()): ?>
                    <tr>
                        <th><?= /* @noEscape */ __('Invoiced') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyInvoiced()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyShipped() && $block->isShipmentSeparately($_item)): ?>
                    <tr>
                        <th><?= /* @noEscape */ __('Shipped') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyShipped()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyRefunded()): ?>
                    <tr>
                        <th><?= /* @noEscape */ __('Refunded') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyRefunded()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyCanceled()): ?>
                    <tr>
                        <th><?= /* @noEscape */ __('Canceled') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyCanceled()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($block->isShipmentSeparately($_item)): ?>
                <table class="qty-table">
                    <tr>
                        <th><?= /* @noEscape */ __('Ordered') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyShipped()): ?>
                    <tr>
                        <th><?= /* @noEscape */ __('Shipped') ?></th>
                        <td><?= /* @noEscape */ $_item->getQtyShipped()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-subtotal">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'subtotal') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-amount">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('tax_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-tax-percent">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayTaxPercent($_item) ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-discont">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= /* @noEscape */ $block->displayPriceAttribute('discount_amount') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
        <td class="col-total last">
            <?php if ($block->canShowPriceInfo($_item)): ?>
                <?= $block->getColumnHtml($_item, 'total') ?>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if ($_showlastRow): ?>
    <tr<?php if (!$block->canDisplayGiftmessage()) { echo ' class="border"'; } ?>>
        <td class="col-product">
            <?php if ($block->getOrderOptions()): ?>
                <dl class="item-options">
                <?php foreach ($block->getOrderOptions() as $option): ?>
                    <dt><?= /* @noEscape */ $option['label'] ?>:</dt>
                    <dd>
                    <?php if (isset($option['custom_view']) && $option['custom_view']): ?>
                        <?= /* @noEscape */ $option['value'] ?>
                    <?php else: ?>
                        <?= /* @noEscape */ $block->truncateString($option['value'], 55, '', $_remainder) ?>
                        <?php if ($_remainder):?>
                            ... <span 
                            id="<?= /* @noEscape */ $_id = 'id' . uniqid() ?>">
                            <?= /* @noEscape */ $_remainder ?></span>
                            <script>
require(['prototype'], function(){

    $('<?= /* @noEscape */ $_id ?>').hide();
    $('<?= /* @noEscape */ $_id ?>').up().observe('mouseover', function(){$('<?= /* @noEscape */ $_id ?>').show();});
    $('<?= /* @noEscape */ $_id ?>').up().observe('mouseout',  function(){$('<?= /* @noEscape */ $_id ?>').hide();});
                            
});
</script>
                        <?php endif;?>
                    <?php endif;?>
                    </dd>
                <?php endforeach; ?>
                </dl>
            <?php else: ?>
                &nbsp;
            <?php endif; ?>
            <?= $block->escapeHtml($_item->getDescription()) ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last">&nbsp;</td>
    </tr>
<?php endif; ?>
