<?php
$blockObj = $block->getLayout()->createBlock(\Mageants\OrderApprovalRules\Block\Frontend\OrderApprovalRules::class);
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?=  /* @noEscape */ __('Orders') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?=  /* @noEscape */ __('Order #') ?></th>
                    <th scope="col" class="col date"><?=  /* @noEscape */ __('Date') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?=  /* @noEscape */ __('Ship To') ?></th>
                    <th scope="col" class="col total"><?=  /* @noEscape */ __('Order Total') ?></th>
                    <th scope="col" class="col status"><?=  /* @noEscape */ __('Status') ?></th>
                    <th scope="col" class="col actions"><?=  /* @noEscape */ __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <?=  /* @noEscape */ $_order->getRealOrderId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date">
                            <?=  /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping">
                            <?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()
                            ->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total">
                            <?=  /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status">
                            <?=  /* @noEscape */ $_order->getStatusLabel() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?=  /* @noEscape */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?=  /* @noEscape */ __('View Order') ?></span>
                            </a>
                            <?php if ($blockObj->salesReorder()->canReorder($_order->getEntityId())):?>
                                <a href="#" data-post='<?=  /* @noEscape */
                                $blockObj->postDataHelper()->getPostData($block->getReorderUrl($_order))
                                ?>' class="action order">
                                    <span><?=  /* @noEscape */ __('Reorder') ?></span>
                                </a>    
                            <?php endif ?>
                            <?php if ($_order->getStatus() == 'orderapproved') { ?>
                                <a href="<?=  /* @noEscape */ $blockObj->getCheckoutUrl($_order->getId()) ?>" 
                                   class="action view"
                                   target="_blank" >
                                    <span>
                                        <?=  /* @noEscape */ __('Complete Order') ?>
                                    </span>
                                </a>
                            <?php } ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?=  /* @noEscape */ __('You have placed no orders.') ?></span></div>
<?php endif ?>
