<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */

$viewModel = $block->getData("viewModel");

$_item = $block->getItem();
$price=$_item->getPrice();

?>
<tr id="order-item-row-<?= /* @noEscape */ $_item->getId() ?>">
    <td class="col name" data-th="<?= $block->escapeHtml(__('Product Name')) ?>">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
            <?php foreach ($_options as $_option): ?>
        <dl class="item-options">
            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
                <?php if (!$block->getPrintStatus()): ?>
                    <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                    <?php else: ?>
                        <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?= /* @noEscape */ nl2br($block->escapeHtml((
                        isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php
            $fullAction=$viewModel->getRequest();
        if ($fullAction=='sales_order_invoice' ||
            $fullAction=='sales_order_view' ||
            $fullAction=='sales_order_shipment') {
                
                $feesIds = $viewModel->getAction($fullAction, $_item);
            if (!empty($feesIds)) {
                ?>
                    <dl class="item-options">
                        <?php foreach ($feesIds as $data) {
                                $ExtraFeeData=$viewModel->getFeesData($data);
                            ?>
                            <dt><?= /* @noEscape */ __($ExtraFeeData['feesname']); ?></dt>
                            <dd><?php if ($ExtraFeeData['type']=='Percentage') {
                                $amount=($price*$ExtraFeeData['amount'])/100; ?>
                                <?= /* @noEscape */
                                    $viewModel->getCurrency($amount);
                                } else {?>
                                    <?= /* @noEscape */
                                     
                                        $viewModel->getCurrency(
                                            $ExtraFeeData['amount'],
                                            true,
                                            false
                                        );
                                }  ?> </dd>
                            
                    <?php }  ?>
                    </dl> 
                <?php
            }
        }
        ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock):?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </td>
    <td class="col sku" 
        data-th="<?= /* @noEscape */ $block->escapeHtml(__('SKU')); ?>">
        <?= /* @noEscape */ $block->prepareSku($block->getSku()) ?>
    </td>
    <td class="col price" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Price')); ?>">
        <?= /* @noEscape */ $block->getItemPriceHtml(); ?>
    </td>
    <td class="col qty" 
        data-th="<?= /* @noEscape */ $block->escapeHtml(__('Qty')); ?>" >
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0):
            ?>
            <li class="item">
                <span class="title"><?= /* @noEscape */ __('Ordered'); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyOrdered()*1 ?></span>
            </li>
        <?php endif; ?>


        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @noEscape */ __('Shipped'); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyShipped()*1 ?></span>
            </li>
        <?php endif; ?>
            
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @noEscape */ __('Canceled'); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyCanceled()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @noEscape */ __('Refunded'); ?></span>
                <span class="content"><?= /* @noEscape */ $block->getItem()->getQtyRefunded()*1 ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </td>
   
    <?php
    if ($fullAction=='sales_order_invoice' || $fullAction=='sales_order_view') {
        ?>
     <td class="col subtotal" data-th="<?= /* @noEscape */ $block->escapeHtml(__('Subtotal')); ?>">
        <?= /* @noEscape */ $block->getItemRowTotalHtml(); ?>
    </td>
    <?php  } ?>
</tr>
