<div  data-role="answerpannel" ></div>

<div class="fieldset">
    <div class="actions">
        <button type="button" title="Ask Question?" 
        class="action primary answerbutton" 
        onclick='jQuery("#product-question-answer-<?= /* @noEscape */ $block->getQuestionId()?>").slideToggle()' >
            <span><?= /* @noEscape */ __('Write Answer');?></span>
        </button>
    </div>
</div>
<div class="answers" >
    <ul>
    <?php foreach ($block->getQuestionsAnswer() as $answer):?>
        <li>
            <div class="amswer " >
                <div class="ansheader">
                    <div class="anstitle">
                        <?= /* @noEscape */ $answer->getAnswer()?>
                    </div>
                    <div class="date-n-customer-name">
                        <div class="name">
                            <span><?= /* @noEscape */ $answer->getName()?></span>
                        </div>
                        <div class="date">
                            <span><?= /* @noEscape */$block->formatDate($answer->getCreatedAt())?></span>
                        </div>

                        <div class="status">
                            <span><?= /* @noEscape */__('Current Status : ')?> 
                            <span class="current-status">
                            <?= /* @noEscape */$block->getStatusText($answer->getStatus())?></span></span>
                        </div>
                    </div>
                    <div class="action">
                        <?php if ($block->isApprove($answer->getStatus())):?>
                            <span class="statuschange">
                            
                            <a class="action-secondary" 
                            href="<?= /* @noEscape */ $block->getRejectUrl($answer->getId())?>">
                            <?= /* @noEscape */ __('Reject Now')?></a></span>
                        <?php else:?>
                            <span class="statuschange">
                            <a class="action-secondary" 
                            href="<?= /* @noEscape */ $block->getApproveUrl($answer->getId())?>">
                            <?= /* @noEscape */  __('Approve Now')?></a></span>
                        <?php endif?>
                    </div>
                </div>
            </div>
        </li>
    <?php endforeach?>
    </ul>
    
    <?php if ($block->canShowLoadMore()):?>
        <?php ?>
    <?php endif?>


    <div id="answer-message" class="messages"></div>
    <div class="answer-form" id="product-question-answer">
        <div id="answer-message"></div>
        <form action="<?= /* @noEscape */$block->getFormUrl() ?>" method="post" class="question-answer-form">
            <ul style="display:none;">
                <li class="ansli">
                    <div class="amswer " >
                        <div class="ansheader">
                            <div class="anstitle"></div>
                            <div class="date-n-customer-name">
                                <div class="name"><span></span></div>
                                <div class="date"><span></span></div>
                                <div class="status"><span></span></div>                            
                                <!--<div class="action"><span class="statuschange">
                                <a href="<?= /* @noEscape */ $block->getRejectUrl('{{ansid}}')?>">
                                <?= /* @noEscape */ __('Reject Now')?></a></span></div>    -->
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
            <input type="hidden" value="<?= /* @noEscape */ $block->getFormKey();?>" name="form_key"/>
            <input type="hidden" value="<?= /* @noEscape */ $block->getApproveStatus()?>" name="adminstatus"/>
            <div class="fieldset-wrapper">
                <div class="admin__fieldset-wrapper-content _hide">
                    <fieldset class="admin__fieldset">                    
                        <div class="admin__field required">
                            <label class="admin__field-label" for="name">
                                <?= /* @noEscape */ __('Name')?> : </label>
                            <div class="admin__field-control">
                                <input type="text" id="name" class="admin__control-text" 
                                required aria-required="true" 
                                value="<?= /* @noEscape */ trim($block->getCustomerName())?>" name="name">
                            </div>                        
                        </div>
                        <div class="admin__field required">
                            <label class="admin__field-label" for="email">
                                <?= /* @noEscape */ __('Email')?>:</label> 
                            <div class="admin__field-control">
                                <input type="email" id="email" name="email" 
                                class="admin__control-text" required aria-required="true"  
                                value="<?= /* @noEscape */ $block->getCustomerEmail()?>">                            
                            </div>
                        </div>
                        <div class="admin__field required">
                            <label  class="admin__field-label" for="question">
                            <?= /* @noEscape */ __('Your Answer')?></label> 
                            <div class="admin__field-control">
                                <textarea name="answer" id="answer" 
                                maxlength="255" required class="admin__control-textarea" 
                                aria-required="true" name="answer"></textarea>                    
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>
    <script>
    require(['productqa'],function($){});
    </script>
</div>