<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Catalog\Block\Product\Gallery $block */
?>
<?php $_width = $block->getImageWidth(); ?>
<div class="product-image-popup" style="width:<?= /* @noEscape */ $_width ?>px;">
    <div class="buttons-set"><a href="#" class="button" role="close-window">
      <span><?= /* @noEscape */ __('Close Window') ?></span></a></div>
    <?php if ($block->getPreviousImageUrl() || $block->getNextImageUrl()): ?>
        <div class="nav">
          <?php if ($_prevUrl = $block->getPreviousImageUrl()): ?>
              <a href="<?= /* @noEscape */ $_prevUrl ?>" class="prev">&laquo; <?= /* @noEscape */ __('Prev') ?></a>
          <?php endif; ?>
          <?php if ($_nextUrl = $block->getNextImageUrl()): ?>
              <a href="<?= /* @noEscape */ $_nextUrl ?>" class="next"><?= /* @noEscape */ __('Next') ?> &raquo;</a>
          <?php endif; ?>
        </div>
    <?php endif; ?>
    <?php if ($_imageTitle = $block->escapeHtml($block->getCurrentImage()->getLabel())): ?>
        <h1 class="image-label"><?= /* @noEscape */ $_imageTitle ?></h1>
    <?php endif; ?>
    <?php
        $imageUrl = $block->getImageUrl();
    ?>
    <img src="<?= /* @noEscape */ $imageUrl ?>"<?php if ($_width): ?> 
    width="<?= /* @noEscape */ $_width ?>"<?php endif; ?> 
    alt="<?= $block->escapeHtml($block->getCurrentImage()->getLabel()) ?>" 
    title="<?= $block->escapeHtml($block->getCurrentImage()->getLabel()) ?>" 
    id="product-gallery-image" class="image" data-mage-init='{"catalogGallery":{}}'/>
    <div class="buttons-set"><a href="#" class="button" role="close-window">
      <span><?= /* @noEscape */ __('Close Window') ?></span></a></div>
    <?php if ($block->getPreviousImageUrl() || $block->getNextImageUrl()): ?>
        <div class="nav">
          <?php if ($_prevUrl = $block->getPreviousImageUrl()): ?>
              <a href="<?= /* @noEscape */ $_prevUrl ?>" class="prev">&laquo; <?= /* @noEscape */ __('Prev') ?></a>
          <?php endif; ?>
          <?php if ($_nextUrl = $block->getNextImageUrl()): ?>
              <a href="<?= /* @noEscape */ $_nextUrl ?>" class="next"><?= /* @noEscape */ __('Next') ?> &raquo;</a>
          <?php endif; ?>
        </div>
    <?php endif; ?>
</div>
